# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_KuGIEsc4NqrBdJEPIBTLHG4Yd7pPgjg
"""

import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()

dir(iris)

iris.feature_names

df = pd.DataFrame(iris.data, columns = iris.feature_names)

df.head()

df['target'] = iris.target
df.head()

iris.target_names # 0: setosa

df[df.target == 1]

df['flower_name'] = df.target.apply(lambda x: iris.target_names[x])
df.head()



# Commented out IPython magic to ensure Python compatibility.
from matplotlib import pyplot as plt
# %matplotlib inline

df0 = df[df.target == 0]
df1 = df[df.target == 1]
df2 = df[df.target == 2]

df0.head()

df1.head()

df2.head()

plt.xlabel('sepal length')
plt.ylabel('sepal width')

plt.scatter(df0['sepal length (cm)'], df0['sepal width (cm)'], color = 'green', marker = 'x')
plt.scatter(df1['sepal length (cm)'], df1['sepal width (cm)'], color = 'blue', marker = '.')
# plt.scatter(df2['sepal length (cm)'], df2['sepal width (cm)'], color = 'red', marker = '*')

plt.xlabel('petal length')
plt.ylabel('petal width')

plt.scatter(df0['petal length (cm)'], df0['petal width (cm)'], color = 'green', marker = 'x')
plt.scatter(df1['petal length (cm)'], df1['petal width (cm)'], color = 'blue', marker = '.')
# plt.scatter(df2['petal length (cm)'], df2['petal width (cm)'], color = 'red', marker = '*')

from sklearn.model_selection import train_test_split

df.head()

X = df.drop(['target', 'flower_name'], axis = 'columns')
X.head()

y = df.target
y.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

len(X_train),len(X_test)

from sklearn.svm import SVC
# model = SVC(gamma = 10)
# model = SVC(C = 1)
model = SVC(kernel = 'linear')

model.fit(X_train, y_train)

model.score(X_test, y_test)
